# Site settings
title: Never say never
header-img: img/home-bg.png
email: tvan262@yahoo.com
copyright_name: tvan262
description: > # this means to ignore newlines until "baseurl:"
  "Whatever a man can do, a woman can do better."
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: tvan262
github_username:  tvan262
learn_profile: tvan262
email_username: tvan262@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
